#include "menu.h"


html_template_3 const menu_item_template::all_template =
{
"<div class = \"menu\"> \n"
    "<style> \n"
        ".collapsible { \n"
            "background-color: #777777; \n"
            "color: white; \n"
            "cursor: crosshair; \n"
            "padding: 6px; \n"
            "border: none; \n"
            "text-align: left; \n"
            "outline: none; \n"
            "font-size: 15px; \n"
            "width: 100%; \n"
        "} \n"
        "\n"
        ".collapsible a { \n"
            "color: #ffffff; \n"
        "} \n"
        "\n"
        ".active { background-color: #555555; } \n"
        ".collapsible:hover { background-color: #ff5555; } \n"
        "\n"
        ".content { \n"
            "padding: 0px 0px 0px 20px; \n"
            "display: none; \n"
            "overflow: hidden; \n"
        "} \n"
        ".content > a { \n"
            "color: #000000; \n"
            "background-color: #ffffff; \n"
        "} \n"
        ".content > a:hover { color: #ff2222; } \n"
        "input { width: 100% }\n"
        "h2 { display: inline }\n"
    "</style>\n"
    "<form action = \"/search\" method = \"get\">\n"
        "<input name = \"search\" type = \"text\" placeholder = \"Поиск корабликов...\" value = \"",
        "\"><br>\n"
    "</form>\n"
    "\n"
    "\n"
    "<button type = \"button\" class = \"collapsible\">\n"
        "вооружение\n"
    "</button><br>\n"
    "<div class = \"content\">\n"
        "<button type = \"button\" class = \"collapsible\">\n"
            "артиллерия\n"
        "</button><br>\n"
        "<div class = \"content\">\n"
            "<a href=\"/armament/guns?sort=caliber,in_service&group=caliber&filter=class,0\">\n"
                "орудия\n"
            "</a><br>\n"
            "<a href=\"/armament/guns?sort=caliber,in_service&group=caliber&filter=class,1\">\n"
                "зенитные орудия\n"
            "</a><br>\n"
            "<a href=\"/armament/guns?sort=caliber,in_service&group=caliber&filter=class,2\">\n"
                "пулеметы\n"
            "</a><br>\n"
        "</div>\n"
        "\n"
        "<button type = \"button\" class = \"collapsible\">\n"
            "торпедное вооружение\n"
        "</button><br>\n"
        "<div class = \"content\">\n"
            "<a href=\"/armament/torpedo?group=caliber,in_service&sort=in_service\">\n"
                "торпеды\n"
            "</a><br>\n"
            "<a href=\"/armament/torpedo_tubes?group=caliber&sort=in_service\">\n"
                "торпедные аппараты\n"
            "</a><br>\n"
        "</div>\n"
        "\n"
        "<button type = \"button\" class = \"collapsible\">\n"
            "авиация\n"
        "</button><br>\n"
        "<div class = \"content\">\n"
            "<a href=\"/aircraft?group=in_service&sort=type,in_service&filter=class,0\">\n"
                "истребители\n"
            "</a><br>\n"
            "<a href=\"/aircraft?group=in_service&sort=type,in_service&filter=class,1\">\n"
                "торпедоносецы\n"
            "</a><br>\n"
            "<a href=\"/aircraft?group=in_service&sort=type,in_service&filter=class,2\">\n"
                "разведчики\n"
            "</a><br>\n"
            "<a href=\"/aircraft?group=in_service&sort=type,in_service&filter=class,3\">\n"
                "пикировщики\n"
            "</a><br>\n"
            "<a href=\"/aircraft?group=in_service&sort=type,in_service&filter=class,4\">\n"
                "легкие бомбардировщики\n"
            "</a><br>\n"
            "<a href=\"/aircraft?group=in_service&sort=type,in_service&filter=class,5\">\n"
                "тяжелые бомбардировщики\n"
            "</a><br>\n"
            "<a href=\"/aircraft?group=in_service&sort=type,in_service&filter=class,6\">\n"
                "гидросамолеты разведчики\n"
            "</a><br>\n"
            "<a href=\"/aircraft?group=in_service&sort=type,in_service&filter=class,7\">\n"
                "летающие лодки\n"
            "</a><br>\n"
            "<a href=\"/aircraft?group=in_service&sort=type,in_service&filter=class,9\">\n"
                "транспорты\n"
            "</a><br>\n"
            "<a href=\"/aircraft?group=in_service&sort=type,in_service&filter=class,10\">\n"
                "реактивные снаряды\n"
            "</a><br>\n"
            "<a href=\"/armament/catapult?group=class&sort=in_service\">\n"
                "катапульты\n"
            "</a><br>\n"
        "</div>\n"
        "\n"
        "<button type = \"button\" class = \"collapsible\">\n"
            "средства обнаружения\n"
        "</button><br>\n"
        "<div class = \"content\">\n"
            "<a href=\"/armament/searcher?group=power&sort=in_service&filter=class,8\">\n"
                "РЛС\n"
            "</a><br>\n"
            "<a href=\"/armament/searcher?group=power&sort=in_service&filter=class,13\">\n"
                "прожектора\n"
            "</a><br>\n"
        "</div>\n"
        "\n"
        "<button type = \"button\" class = \"collapsible\">\n"
            "мины и глубинные бомбы\n"
        "</button><br>\n"
        "<div class = \"content\">\n"
            "<a href=\"/armament/mines_charges?filter=class,4&sort=mass_ex\">\n"
                "глубинные бомбы\n"
            "</a><br>\n"
            "<a href=\"/armament/mines_charges?filter=class,6&sort=mass_ex\">\n"
                "мины\n"
            "</a><br>\n"
        "</div>\n"
    "</div>\n"
    "<br>",
    
    "<script>\n"
        "var coll = document.getElementsByClassName(\"collapsible\");\n"
        "var i;\n"
        "\n"
        "for (i = 0; i < coll.length; i++) {\n"
            "coll[i].addEventListener(\"click\", function() {\n"
                "this.classList.toggle(\"active\");\n"
                "var content = this.nextElementSibling.nextElementSibling;\n"
                "if (content.style.display === \"block\") {\n"
                    "content.style.display = \"none\";\n"
                "} else {\n"
                    "content.style.display = \"block\";\n"
                "}\n"
            "});\n"
        "}\n"
    "</script>\n"
"</div>\n"
};
