#include "html_template.h"

extern const html_template_3 style;

const html_template_3 style = 
{
"<!DOCTYPE html>\n"
"<html>\n"
    "<head>\n"
        "<title>\n",

        "</title>\n"
        "<link rel=\"icon\" type=\"image/x-icon\" href=\"/pictures/favicon.ico\">"
    "</head>\n"
    "<body>\n"
        "<style>\n"
            "* { font-size: 16px; }\n"
            ".wrapper { display: flex; }\n"
            "footer {\n"
                "display: table;\n"
                "color: #111111;\n"
                "font-size: 10px;\n"
                "text-align: center;\n"
                "margin-left: auto;\n"
                "margin-right: auto;\n"
                "border-top: 2px solid black;"
            "}\n"

            ".menu {\n"
                "display: inline;\n"
                "min-width: 230px;\n"
                "width:     230px;\n"
                "max-width: 230px;\n"
                "padding: 0px 10px 0px 0px;\n"
            "}\n"
            ".main { display: inline; }\n"
            ".main img {\n"
                "object-fit: contain;\n"
                "min-width: 180px;\n"
                "max-width: 180px;\n"
                "min-height: 180px;\n"
                "max-height: 180px;\n"
                "background-color: #f5f5f5;\n"
            "}\n"
            ".main li {\n"
                "display: inline-block;\n"
                "margin: 10px;\n"
                "max-width: 180px;\n"
                "vertical-align: top;\n"
            "}\n"
            ".main ul {\n"
                "list-style-type: disc;\n"
            "}\n"

            ".menu button {\n"
                "background-color: #777777;\n"
                "color: white;\n"
                "cursor: crosshair;\n"
                "padding: 6px;\n"
                "border: none;\n"
                "text-align: left;\n"
                "outline: none;\n"
                "width: 100%;\n"
            "}\n"
            ".menu button a {\n"
                "color: #ffffff;\n"
            "}\n"
            ".active { background-color: #555555; }\n"
            ".menu button:hover { background-color: #ff5555; }\n"
            ".menu button:focus { background-color: #6666ff; }\n"
            ".menu button > a:focus { color: #aaeeff; }\n"
            "con-tent {\n"
                "padding: 0px 0px 0px 30px;\n"
                "display: none;\n"
                "overflow: hidden;\n"
            "}\n"
            "con-tent > a {\n"
                "color: #000000;\n"
                "background-color: #ffffff;\n"
            "}\n"
            "con-tent > a:hover { color: #ff2222; }\n"
            "con-tent > a:focus { color: #2222ff; }\n"
            ".menu_link > a {\n"
                "color: #000000;\n"
                "background-color: #ffffff;\n"
            "}\n"
            ".menu_link > a:hover { color: #ff2222; }\n"
            ".menu_link > a:focus { color: #2222ff; }\n"

            ".ship_armament tr { white-space: nowrap; }\n"
            ".ship_armament tr.header    { background: #fff8dc; }\n"
            ".ship_armament tr.general   { background: #f8ffdc; }\n"
            ".ship_armament tr.guns      { background: #cdffcc; }\n"
            ".ship_armament tr.torpedo   { background: #c0ffef; }\n"
            ".ship_armament tr.throwers  { background: #9fffe0; }\n"
            ".ship_armament tr.searchers { background: #ffffc0; }\n"
            ".ship_armament tr.catapult  { background: #e4fcff; }\n"
            ".ship_armament tr.aircraft  { background: #d0efff; }\n"
            ".ship_armament tr.propulsion{ background: #ffe8c8; }\n"
            ".ship_armament th { min-width: 180px }\n"
            
            ".armament { table-layout: fixed; }\n"
            ".armament td {\n"
                "min-width: 150px;\n"
                "max-width: 150px;\n"
            "}\n"
            
            ".short_info th      { min-width: 120px; }\n"
            ".short_info a       { color: #222222; }\n"
            ".short_info a:hover { color: #ff2222; }\n"
            ".short_info a:focus { color: #2222ff; }\n"
            
            ".long_info { width: min-content; }\n"
            ".long_info ul { min-width: calc(100vw - 230px - 100px); }\n"
            
            ".search { width: 97%; margin: 10px 20px 20px 0; }\n"
            ".search:focus { outline-color: #2222ff; }\n"
            "input { margin: 0 0 0 0; }\n"
            "h2 { display: inline; }\n"
            "ship-cnt { float:right; }\n"
            "b-t { font-weight: bold; }\n"
            
            ".tooltip {\n"
                "position: relative;\n"
                "display: inline-block;\n"
                "background-color: #222222;\n"
            "}\n"
            ".tooltip .tooltiptext {\n"
                "visibility: hidden;\n"
                "width: 200px;\n"
                "background-color: #222222;\n"
                "color: #ffffff;\n"
                "padding: 5px 15px 5px 15px;\n"
                "left: 105%;\n"

                "position: absolute;\n"
                "z-index: 1;\n"
            "}\n"
            ".tooltip:hover .tooltiptext {\n"
                "visibility: visible;\n"
            "}\n"

        "</style>\n"
        "<div class=\"wrapper\">\n",

        "</div>\n"
        "<footer>\n"
            "disclaimer:\n"
            "рассматриваемый период: 07.12.1941 - 02.09.1945<br>\n"
            "и да, здесь не просто могут быть... а гарантированно есть ошибки и неточности!<br>\n"
            "сайт в разработке и хостится даже не в гараже (нету у меня гаража), поэтому SLA 9.999%<br>\n"
        "</footer>\n"
    "</body>\n"
"</html>"
};
